### ISSUE TITLE
No Setup Instructions for Slack Provider

### ISSUE THREAD

**Issue by Kaszanas** [gitroomhq/postiz-docs#12]
Based on the .env example and its contents it suggests that the:

```env
SLACK_ID=""
SLACK_SECRET=""
SLACK_SIGNING_SECRET=""
```

Would allow for the Slack provider setup. Unfortunately this is not available in the documentation under providers.

**Comment by egelhaus** [comment]
Created an PR on that, should be merged soon 👍 
#34

**Comment by Kaszanas** [comment]
I see this was merged @jamesread
Can I close?
