### ISSUE TITLE
No Setup Instructions for Pinterest Provider

### ISSUE THREAD

**Issue by Kaszanas** [gitroomhq/postiz-docs#14]
Based on the .env example and its contents it suggests that the:

```env
PINTEREST_CLIENT_ID=""
PINTEREST_CLIENT_SECRET=""
```

Would allow for the Pinterest provider setup. Unfortunately this is not available in the documentation under providers.

**Comment by egelhaus** [comment]
@Kaszanas Added an PR to that, should be added soon.

**Comment by Kaszanas** [comment]
I see it was merged closing @jamesread
