### ISSUE TITLE
No Setup Instructions for GitHub Provider

### ISSUE THREAD

**Issue by Kaszanas** [gitroomhq/postiz-docs#16]
Based on the .env example and its contents it suggests that the:

```env
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""
```

Would allow for the GitHub provider setup. Unfortunately this is not available in the documentation under providers.

**Comment by egelhaus** [comment]
@Kaszanas GitHub isn’t an Provider, it’s just being used to sync stars, it’s only really used in platform.postiz.com, as @jamesread explained in the Discord Server:
https://discord.com/channels/1243410146097500202/1244293128370786364/1302074033038299207

**Comment by jamesread** [comment]
I'm closing this for now, as there isn't really the need to make the GitHub analytics stuff usable in the self-hosted version. It's mostly to support @nevo-david 's paid business (gitroom) which allows owners of Git repositories to promote their application. 

If you're curious, the code is still there, and here is some quick documentation about how you can enable it - again, I think it's not really many people;

* Setup a OAuth app on GitHub, under the developers section -> OAuth. Set the redirect URI to `postiz.example.com/settings` (it doesn't use the standard OAuth integrations path). 
* Unset IS_GENERAL in your environment variables
* Set GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET environment variables as per your registered app. 
* Restart Postiz
* Go to the new "Settings" tab, and connect you repository - I connected OliveTin to make some quick screenshots; 

![image](https://github.com/user-attachments/assets/7dbf4fa4-43fe-4323-947c-d47811ab7349)

* Go to the "Analytics" page and look at your repo stats; 

![image](https://github.com/user-attachments/assets/3b64dc80-7d8e-4ee0-8dd1-041798789422)

You can see  this provides a daily stats breakdown, as well as a "Check Launch" button which simply takes you through the the calendar view for that day (to see social posts posted on that day). 

Now you know what the GitHub integration is for, and how to use it if you own a GitHub repo and want to use Postiz in that way.

Note that by not setting IS_GENERAL, will affect a bunch of other stuff at the moment (most obviously the logo, product name, etc), but it also enables a bunch of other features most people probably don't want.

Anyway, curiosity satisfied hopefully, it's for Nevo, who built the project :-)
