### ISSUE TITLE
No Setup Instructions for Beehiive/Beehiiv? Provider

### ISSUE THREAD

**Issue by Kaszanas** [gitroomhq/postiz-docs#18]
Based on the .env example and its contents it suggests that the:

```
BEEHIIVE_API_KEY=""
BEEHIIVE_PUBLICATION_ID=""
```

Would allow for the GitHub provider setup. Unfortunately this is not available in the documentation under providers.

Also it seems that the `.env` key names do not relate well to which platform the provider is supposed to support.

**Comment by jamesread** [comment]
This is just the newsletter service being used by the paid version - it's of no use to self hosters :-)
