### ISSUE TITLE
Feedback for “Discord”

### ISSUE THREAD

**Issue by HunterKingNola** [gitroomhq/postiz-docs#26]
Step #4 is vague about where to put redirect URI. I don't see an explicit field for that in any of the Discord App options.

**Comment by egelhaus** [comment]
Hey @HunterKingNola , you have to set the redirect URI in the OAuth Tab of the Discord Bot, I'll be making an Update on the Discord Doc about that, thanks for the Info.

**Comment by jamesread** [comment]
On top of @egelhaus 's PR fix (thanks for that), I've just added a screenshot and pointed out that it's found in the OAuth2 section, so I hope that this is considered fixed :-) Please reopen if you think it could be improved. 

![image](https://github.com/user-attachments/assets/05728302-1af5-451c-9098-c7cc34618369)
