### ISSUE TITLE
No Setup Instructions for YouTube Provider

### ISSUE THREAD

**Issue by Kaszanas** [gitroomhq/postiz-docs#9]
Based on the `.env` example and its contents it suggests that the:

```
YOUTUBE_CLIENT_ID=""
YOUTUBE_CLIENT_SECRET=""
```

Would allow for the YouTube provider setup. Unfortunately this is not available in the documentation under providers.

**Comment by Kaszanas** [comment]
PR: https://github.com/gitroomhq/postiz-docs/pull/10 was merged, I am closing this.

**Comment by jamesread** [comment]
Accepted your PR! Now there are docs! :-D

We'll improve them as we go. https://docs.postiz.com/providers/youtube
